### ISSUE TITLE
When does it lock?

### ISSUE THREAD

**Issue by JonFranchi** [chilts/mongodb-lock#6]
I was thinking about how to implement something like this for myself when I came across this repo.  However, I'm confused as I tried to spin up an example and I am not getting expected results.  For a given lock name, I can acquire the lock 100% of the time.  I would expect that if I tried to acquire the lock seconds after successfully acquiring, it would fail to acquire until it expired.  I would like to schedule some crons in a node app with multiple instances and prevent multiple executions of same job.

This seemed like I had configured something incorrectly, so I went and looked at the code.  Sure enough, it is generating a unique key every time and using that as part of the insert, meaning every attempt to acquire a lock for a lock name is going to succeed and create a unique lock.

Am I missing something?  Is this library for a different purpose than I am thinking?

**Comment by larafale** [comment]
same here, new lock on each acquire, lib not working.

**Comment by chilts** [comment]
Apologies for this. I took a look at the code earlier today and I've spent a fair bit of time updating to the MongoDB Driver v3. I wonder if these things weren't working since MongoDB Lock had been expecting v2 of the driver.

Either way I've managed get all the tests working again, and finally, after all this time, I've released v1.0.0 to npm. :)

Please install it and give it a try. Many thanks for bumping this issue @larafale.

**Comment by chilts** [comment]
https://www.npmjs.com/package/mongodb-lock

**Comment by larafale** [comment]
oh cool, I did went another path concerning my issue, but will definitely give it another shot next time :) thanks for contributing to OSS, keep it up brother ^^
